name: "Install mdbook"
description: "Install mdbook based on Cargo.toml version"

runs:
  using: "composite"
  steps:
    - name: Install mdbook
      run: |
        REQUIRED_VERSION="$(grep '^mdbook-core' Cargo.toml | sed 's/.*"\([^"]*\)".*/\1/')"
        if command -v mdbook >/dev/null 2>&1; then
          INSTALLED_VERSION="$(mdbook --version | awk '{print $2}')"
          if [ "$INSTALLED_VERSION" = "$REQUIRED_VERSION" ]; then
            echo "mdbook $INSTALLED_VERSION is already installed."
          else
            echo "mdbook $INSTALLED_VERSION is installed but we need $REQUIRED_VERSION. Reinstalling..."
            cargo install mdbook --version "$REQUIRED_VERSION" --force
          fi
        else
          echo "mdbook not found. Installing version $REQUIRED_VERSION..."
          cargo install mdbook --version "$REQUIRED_VERSION" --force
        fi
      shell: bash
