[book]
authors = ["MR-Addict"]
description = "This is a mdbook preprocessor plugin that allows you embed apps to your book, like youtube, codepen and some other apps"
language = "en"
multilingual = false
src = "src"
title = "Mdbook Embedify"

[rust]
edition = "2021" # the default edition for code blocks

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

[output.html]
default-theme = "Light"
preferred-dark-theme = "Ayu"
curly-quotes = true
mathjax-support = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/mr-addict/mdbook-embedify"
edit-url-template = "https://github.com/mr-addict/mdbook-embedify/edit/main/example/{path}"
additional-css = ["assets/css/patch.css"]

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[preprocessor.embedify]
command = "target/release/mdbook-embedify.exe"
scroll-to-top.enable = true

announcement-banner.enable = true
announcement-banner.id = "0.2.3"
announcement-banner.theme = "default"
announcement-banner.message = "*Version **0.2.3** now has relased, check it out [here](https://github.com/MR-Addict/mdbook-embedify/releases/tag/0.2.3).*"
